twig:
    file_name_pattern: '*.twig'
    globals:
        app_version: '%app.version%'
        app_build: '%app.build%'
        app_commit: '%app.commit%'

when@test:
    twig:
        strict_variables: true
