inherit: true

filter:
    paths: ['src/*']
    excluded_paths: ['vendor/*', 'tests/*', 'bin/*', 'build/*', 'config/*', 'data/*', 'resources/*']

checks:
    php:
        code_rating: true
        duplication: true
        remove_extra_empty_lines: true
        remove_php_closing_tag: true
        remove_trailing_whitespace: true
        fix_use_statements:
            remove_unused: true
            preserve_multiple: false
            preserve_blanklines: true
            order_alphabetically: true
        fix_php_opening_tag: true
        fix_linefeed: true
        fix_line_ending: true
        fix_identation_4spaces: true
        fix_doc_comments: true
        no_debug_code: true

coding_style:
    php:
        spaces:
            around_operators:
                bitwise: false

before_commands:
    - 'sudo composer self-update'
    - 'composer install --no-interaction'

build:
    nodes:
        php72:
            environment:
                php: '7.2'

            tests:
                override:
                    - php-scrutinizer-run --enable-security-analysis
                    -
                        command: 'vendor/bin/phpunit -c phpunit.xml'
                        coverage:
                            file: 'build/logs/clover.xml'
                            format: 'clover'

tools:
    external_code_coverage: false

    sensiolabs_security_checker: true

    php_changetracking: true

    php_code_coverage:
        enabled: true

    php_code_sniffer:
        enabled: true
        config:
            standard: PSR2
        filter:
            paths: ["src/*", "tests/*"]

    php_cpd:
        enabled: true
        excluded_dirs: ["build/*", "tests", "vendor"]

    php_analyzer:
        enabled: true
        filter:
            paths: ["src/*", "tests/*"]

    php_mess_detector:
        enabled: true
        filter:
            paths: ["src/*"]
        config:
            ruleset: "phpmd.xml"

    php_pdepend:
        enabled: true
        excluded_dirs: ["build", "tests", "vendor"]

    php_loc:
            enabled: true
            excluded_dirs: ["vendor", "tests", "bin", "build", "resources", "config", "data"]

    php_cpd:
            enabled: true
            excluded_dirs: ["vendor", "tests", "bin", "build", "resources", "config", "data"]
