inherit: true

filter:
    paths: ['src/*']
    excluded_paths: ['vendor/*', 'tests/*', 'bin/*', 'build/*', 'config/*', 'data/*', 'resources/*']

checks:
    php:
        code_rating: true
        duplication: true
        remove_extra_empty_lines: true
        remove_php_closing_tag: true
        remove_trailing_whitespace: true
        fix_use_statements:
            remove_unused: true
            preserve_multiple: false
            preserve_blanklines: true
            order_alphabetically: true
        fix_php_opening_tag: true
        fix_linefeed: true
        fix_line_ending: true
        fix_identation_4spaces: true
        fix_doc_comments: true

coding_style:
    php:
        spaces:
            around_operators:
                bitwise: false

tools:
    php_code_coverage: true

before_commands:
    - 'sudo composer self-update'
    - 'composer install --prefer-source --no-interaction'

build:
    environment:
        php: '5.6'
    tests:
        override:
            -
                command: 'vendor/bin/phpunit -c phpunit.xml'
                coverage:
                    file: 'build/logs/clover.xml'
                    format: 'clover'

tools:
    external_code_coverage:
        enabled: false
    php_code_coverage:
        enabled: true
    php_code_sniffer:
        enabled: true
        config:
            standard: PSR2
    php_mess_detector:
        enabled: true
        config:
            ruleset: phpmd.xml
    php_analyzer: true
    php_loc:
            enabled: true
            excluded_dirs: [vendor, tests, bin, build, resources, config, data]
    php_cpd:
            enabled: true
            excluded_dirs: [vendor, tests, bin, build, resources, config, data]
