filter:
    paths:
      - 'src/*'
    excluded_paths:
      - 'vendor/*'
      - 'tests/*'
      - 'bin/*'
      - 'build/*'
      - 'config/*'
      - 'data/*'
      - 'resources/*'

coding_style:
    php:
        spaces:
            around_operators:
                bitwise: false

before_commands:
    - 'sudo composer self-update'
    - 'composer install --prefer-source --no-interaction'

build:
    environment:
        php: '5.6'
    tests:
        override:
            -
                command: 'vendor/bin/phpunit -c phpunit.xml'
                coverage:
                    file: 'build/logs/clover.xml'
                    format: 'clover'

tools:
    external_code_coverage:
        enabled: false

    php_code_coverage:
        enabled:              true

    php_code_sniffer:
        enabled:              true
        config:
            standard:         PSR2
            sniffs:
                generic:
                    files:
                        one_class_per_file_sniff: false

    # Copy/Paste Detector
    php_cpd:
        enabled:              true
        excluded_dirs:
            - bin
            - tests
            - vendor
            - build
            - config
            - data
            - resources

    # PHP CS Fixer
    php_cs_fixer:
        enabled:              true
        config:
            level:            psr2

    # Analyzes the size and structure of a PHP project.
    php_loc:
        enabled:              true
        excluded_dirs:
            - bin
            - tests
            - vendor
            - build
            - config
            - data
            - resources

    # PHP Mess Detector
    php_mess_detector:
        enabled:              true
        extensions:
            - php
        config:
            ruleset: phpmd.xml

    # Analyzes the size and structure of a PHP project.
    php_pdepend:
        enabled:              true
        excluded_dirs:
            - bin
            - tests
            - vendor
            - build
            - config
            - data
            - resources

    # Runs Scrutinizer's PHP Analyzer Tool
    php_analyzer:
        enabled:              true
