name: CI

on:
    push:
        branches: [ "main", "master" ]
    pull_request:
        branches: [ "main", "master" ]

jobs:
    tests:
        name: PHP ${{ matrix.php }} Tests
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php: ['8.4']

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, dom, filter, gd, iconv, json, libxml, openssl
                  coverage: pcov

            - name: Install dependencies
              run: composer install --no-interaction --prefer-dist

            - name: PHP Code Sniffer (PSR12)
              run: composer run qa:phpcs

            - name: PHP CS Fixer (dry-run)
              run: composer run qa:php-cs-fixer:dry-run

            - name: Rector (dry-run)
              run: composer run qa:rector:dry-run

            - name: PHP CPD
              run: composer run qa:phpcpd

            - name: PHP LOC
              run: composer run qa:phploc

            - name: PHP Stan
              run: composer run qa:phpstan

            - name: Psalm
              run: composer run qa:psalm

            - name: Deptrac
              run: composer run qa:deptrac

            - name: Run Tests
              run: vendor/bin/phpunit -c phpunit.dist.xml --coverage-clover coverage.xml

            - name: Upload coverage to Codecov
              uses: codecov/codecov-action@v4
              with:
                files: ./coverage.xml
